openapi: '3.0.2'
info:
  title: 'Beacons Service V1'
  description: 'Sample Beacons microservice'
  version: '1'
paths:
  /v1/beacons/get_beacons:
    post:
      tags:
        - v1/beacons
      operationId: 'get_beacons'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                filter:
                  $ref: '#/components/schemas/FilterParams'
                paging:
                  $ref: '#/components/schemas/PagingParams'
      responses: 
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataPage'
  /v1/beacons/get_beacon_by_id:
    post:
      tags:
        - v1/beacons
      operationId: 'get_beacon_by_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                beacon_id:
                  type: string
              required:
                - beacon_id
      responses: 
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeaconV1'
  /v1/beacons/get_beacon_by_udi:
    post:
      tags:
        - v1/beacons
      operationId: 'get_beacon_by_udi'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                udi:
                  type: string
              required:
                - udi
      responses: 
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeaconV1'
  /v1/beacons/calculate_position:
    post:
      tags:
        - v1/beacons
      operationId: 'calculate_position'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                site_id:
                  type: string
                udis:
                  $ref: '#/components/schemas/ArrayOfStrings'
              required:
                - udi
      responses: 
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CenterObjectV1'
  /v1/beacons/create_beacon:
    post:
      tags:
        - v1/beacons
      operationId: 'create_beacon'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                beacon:
                  $ref: '#/components/schemas/BeaconV1'
              required:
                - beacon
      responses: 
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeaconV1'
  /v1/beacons/update_beacon:
    post:
      tags:
        - v1/beacons
      operationId: 'update_beacon'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                beacon:
                  $ref: '#/components/schemas/BeaconV1'
              required:
                - beacon
      responses: 
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeaconV1'
  /v1/beacons/delete_beacon_by_id:
    post:
      tags:
        - v1/beacons
      operationId: 'delete_beacon_by_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                beacon_id:
                  type: string
              required:
                - beacon_id
      responses: 
        200:
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeaconV1'
components:
  schemas:
    CenterObjectV1:
      type: object
      properties:
        type: 
          type: string
        coordinates:
          $ref: '#/components/schemas/ArrayOfDouble'
    BeaconV1:
      type: object
      properties:
        id:
          type: string
        site_id:
          type: string
        type:
          type: string
        udi:
          type: string
        label:
          type: string
        center:
          $ref: '#/components/schemas/CenterObjectV1'
    DataPage:
      type: object
      properties:
        data: 
          type: array
          items:
            $ref: '#/components/schemas/BeaconV1'
        total:
          type: integer
    FilterParams:
      type: object
      additionalProperties:
        type: string
    PagingParams:
      type: object
      properties:
        skip:
          type: integer
        take:
          type: integer
        total: 
          type: boolean
      required:
        - total
    ArrayOfDouble:
      type: array
      items: 
        type: number
    ArrayOfStrings:
      type: array
      items: 
        type: string
