---
  apiVersion: v1
  kind: Service
  metadata:
    name: postgres
    labels: 
      app: postgres
  spec:
    type: NodePort
    ports:
    - port: 5432
      nodePort: 32432
      protocol: TCP
    selector:
      app: postgres
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgres-deploy
    labels:
      app: postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    minReadySeconds: 5
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
          - name: postgres-pod
            image: postgres:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: credentials
                    key: postgres_user
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: credentials
                    key: postgres_pass
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: config
                    key: postgres_db
