version: '3.3'

services:

  app:
    image: ${IMAGE:-app}
    ports:
      - "8080:8080" 
      - "8090:8090" 
    depends_on:
      - mongo
    environment:
      - HTTP_PORT=8080
      - MONGO_ENABLED=true
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      # - POSTGRES_ENABLED=true
      # - POSTGRES_SERVICE_HOST=postgres
      # - POSTGRES_SERVICE_PORT=5432
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASS=postgres
      # - POSTGRES_DB=app
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true
      

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: app

  mongo:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
