---
  # Container descriptor
  - descriptor: "pip-services:context-info:default:default:1.0"
    name: "beacons"
    description: "Beacons microservice"
  
  # Console logger
  - descriptor: "pip-services:logger:console:default:1.0"
    level: "trace"
  
  # Perfomance counter that post values to log
  - descriptor: "pip-services:counters:log:default:1.0"
  
  {{^if MONGO_ENABLED}}{{^if POSTGRES_ENABLED}}{{^if FILE_ENABLED}}
  # Memory persistence
  - descriptor: "beacons:persistence:memory:default:1.0"
  {{/if}}{{/if}}{{/if}}
  
  {{#if FILE_ENABLED}}
  # File persistence
  - descriptor: "beacons:persistence:file:default:1.0"
    path: {{FILE_PATH}}{{^if FILE_PATH}}"./data/beacons.json"{{/if}}
  {{/if}}
  
  {{#if MONGO_ENABLED}}
  # MongoDb persistence
  - descriptor: "beacons:persistence:mongodb:default:1.0"
    connection:
      uri: {{MONGO_SERVICE_URI}}
      host: {{MONGO_SERVICE_HOST}}{{^if MONGO_SERVICE_HOST}}"localhost"{{/if}}
      port: {{MONGO_SERVICE_PORT}}{{^if MONGO_SERVICE_PORT}}27017{{/if}}
      database: {{MONGO_DB}}{{^if MONGO_DB}}"test"{{/if}}
  {{/if}}

  {{#if POSTGRES_ENABLED}}
  # PostreSQL Persistence
  - descriptor: "beacons:persistence:postgres:default:1.0"
    connection:
      uri: {{{POSTGRES_SERVICE_URI}}}
      host: {{{POSTGRES_SERVICE_HOST}}}{{#unless POSTGRES_SERVICE_HOST}}localhost{{/unless}}
      port: {{POSTGRES_SERVICE_PORT}}{{#unless POSTGRES_SERVICE_PORT}}5432{{/unless}}
      database: {{POSTGRES_DB}}{{#unless POSTGRES_DB}}app{{/unless}}
    credential:
      username: {{POSTGRES_USER}}
      password: {{POSTGRES_PASS}}
  {{/if}}
  
  
  # Controller
  - descriptor: "beacons:controller:default:default:1.0"

{{#if HTTP_ENABLED}}
  # Shared HTTP Endpoint
  - descriptor: "pip-services:endpoint:http:default:1.0"
    connection:
      protocol: http
      host: 0.0.0.0
      port: {{HTTP_PORT}}{{#unless HTTP_PORT}}8080{{/unless}}

  # HTTP Service V1
  - descriptor: "beacons:service:commandable-http:default:1.0"
    swagger:
      enable: true
      auto: true
      name: "Beacons Service V1"
      description: "Sample beacons microservice"

  # Hearbeat service
  - descriptor: "pip-services:heartbeat-service:http:default:1.0"

  # Status service
  - descriptor: "pip-services:status-service:http:default:1.0"  
{{/if}}

{{#if GRPC_ENABLED}}
  # Shared GRPC endpoint
  - descriptor: "pip-services:endpoint:grpc:default:1.0"
    connection:
      protocol: "http"
      host: "0.0.0.0"
      port: {{GRPC_SERVICE_PORT}}{{#unless GRPC_SERVICE_PORT}}8090{{/unless}}

  # GRPC endpoint version 1.0
  - descriptor: "beacons:service:grpc:default:1.0"

  # Commandable GRPC endpoint version 1.0
  - descriptor: "beacons:service:commandable-grpc:command:1.0"
{{/if}}